### ISSUE TITLE
unified_question.txt is not parsed to replace variables with values?

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#100]
A raiz de los cambios hechos en #99 , he cambiado parte del contexto de los problemas Bayesianos y lo he puesto en la pregunta. La cosa deberia haber quedado:

> Imagine a group of 2000 women at age 40 that go through a massive screening. Of those with a positive mammogram, how many would you expect to actually have breast cancer?

Pero la pregunta se muestra asi:

> Imagine a group of prevalence_02_variable women at age age_variable that go through a massive screening. Of those with a positive mammogram, how many would you expect to actually have breast cancer?

Las variables prevalence_02_variable y age_variable no se cambian por sus valores...

**Comment by nik0lai** [comment]
En el template de esta pregunta se usan los codigos para llamar a embedded data en qualtrics. La versión correcta es esta:

> Imagine a group of ${e://Field/prevalence_class_0} women at age ${e://Field/woman_age_01} that go through a routine screening. Of those with a positive ${e://Field/positive_test_result_0}, how many would you expect to actually have ${e://Field/medical_condition_0}?

y queda así:

> Imagine a group of 2000 women at age 40 that go through a routine screening. Of those with a positive mammogram, how many would you expect to actually have breast cancer?
