### ISSUE TITLE
Plausible responses to display on follow-up

### ISSUE THREAD

**Issue by nik0lai** [gorkang/R_conditions_creation#103]
To display the follow-up item in the book some plausible responses are needed. Now there is an absolute number and a percentage.

**Comment by gorkang** [comment]
En el apartado 14.6 Follow-up, veo lo siguiente:

```
fu_ins_0

Remember that:

It is estimated that trisomy 21 is present in 40 out of 2000 women.

In your response to the previous problem, you said that 20 of those with a positive mammogram/test result actually have the medical condition (breast cancer/Down’s syndrome).

...
```

Ese **20** es a lo que te refieres? Tal y como esta me parece OK.

**Comment by nik0lai** [comment]
Si. Cada vez que se compila el libro elije una prevalencia al azar y la asocia a una de las dos respuestas posibles: 20 u 11%.
