### ISSUE TITLE
Escala deberia cambiar en "How small this risk should be for you to recommend it"

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#106]
Ahora mismo si dicen que NO a Follow Up, se les pregunta:

> Remember the biopsy has a 1% procedure-related risk of complications: 
> 
> How small this risk should be for you to recommend it (0-100%)

Y la escala va de 0 a 100 en intervalos de 1. Esto implica que la UNICA respuesta razonable es decir 0.

- [ ] Hay que cambiar la escala para que vaya de de 0 a 10, en intervalos de 0.1 (de ese modo tb sirve cuando el riesgo es 10%).

**Comment by nik0lai** [comment]
fixed.
