### ISSUE TITLE
Escala NFC

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#107]
Veo dos problemas en la escala NFC:

- [x] La escala esta al reves de lo habitual (agree a la izquierda y disagree a la derecha)

Tenemos:

> 1verystrongagreement | 2 | 3moderateagreement | 4 | 5neitheragreementnordisagreement | 6 | 7moderatedisagreement | 8 | 9verystrongdisagreement

Y en el doc indica:

>  1 = extremely uncharacteristic; 2 = somewhat uncharacteristic; 3 = uncertain; 4 = somewhat characteristic; 5 = extremely characteristic.

**Comment by nik0lai** [comment]
estamos usando etiquetas del artículo del 1982 (ver issue #81).
Queda pendiente invertir el orden de las etiquetas (disagree a la izquierda, agree a la derecha).

**Comment by nik0lai** [comment]
Escala invertida.
