### ISSUE TITLE
Documentos de referencia para cada escala

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#108]
En la carpeta "Experimento 1/Individual differences/Scales" hay algunas escalas donde tenemos multiples documentos (e.g. NFC). Esto hace que sea dificil saber cual de las versiones usamos.

- [x] Dejar unicamente el documento de la escala que usamos en el experimento en la carpeta de cada escala, y crear una subcarpeta "Otros" con el resto de documentos.

**Comment by nik0lai** [comment]
Quedó solamente el artículo de donde se sacó la escala. En algunos casos la escala (los items) y una breve descripción está en dos pdf. En estos casos los items están aun así sólo en uno de ellos. Ante cualquier duda hay que buscar en los issues resueltos.
