### ISSUE TITLE
How strongly would you recommend her to take the screening test?

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#109]
Hacemos la siguiente pregunta:

- How strongly would you recommend her to take the screening test?

No seria mejor (?):
- How strongly you think she should take the screening test?

El problema que veo es que recomendar implica responsabilidad, pero pensar es gratis. Tal vez pienso que el test es malo, pero no le recomendaria no tomarlo... imagina q se muere por mi culpa...

IMPORTANTE: Si cambiamos recommend por think... tenemos que cambiar tambien #110

**Comment by nik0lai** [comment]
Me parece buen cambio. No sólo por responsabilidad, puede ser simplemente que yo no debería meterme en las decisiones de otros. Esta es más volcada a lo que piensa el participante.

**Comment by nik0lai** [comment]
done.
