### ISSUE TITLE
Which factors influenced your recommendation

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#110]
Ahora mismo la opcion "Other" es obligatoria.

Tenemos 2 opciones:

1. Hacerla no obligatoria (duh)
2. Cambiar "Other" por "Write down the main factor for you"

Ademas, si cambiamos recommend por think (#109 ), en esta pregunta habria que cambiar el wording:

- [x] Which factors influenced your recommendation -> Which factors influenced your previous response (How strongly you think she should take the screening test?)

**Comment by nik0lai** [comment]
"Other" es parte de un sólo item que incluye todos los factores que se mencionan antes. Esto hace que si pones respuesta forzada es en todos o en ninguno. Así que la opción 1 no es hacible sin separar todos los factores en escalas distintas (lo que lo hace feo).

**Comment by nik0lai** [comment]
Usar embedded data para insert NO en

>  Which factors influenced your recommendation -> Which factors influenced your previous response (How strongly you think she should NOT take the screening test?)

**Comment by nik0lai** [comment]
En #109 se hizo el cambio de acuerdo a la sugerencia y también se cambió la pregunta del followup de acuerdo a la sugerencia de este issue.
Además cambié "other" por "Write down the main factor for you" porque no se puede hacer sólo "other" no obligatoria. Así que todos los items de que factores influenciaron tu respuesta quedan como obligatorios.
