### ISSUE TITLE
Usar Titulos para separar bloques

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#112]
Para que los participantes diferencien bien los distintos bloques del experimento necesitamos introducir titulos que claramente definan estos bloques. Los titulos tienen que estar con un tipo de letra mas grande y en negrita (tal vez  H1 o H2?). Tendremos 4 bloques:

- [x] - Medical condition 1/2
- [x] - Medical condition 2/2
- [x] - Personality scales
- [x] - Cognitive scales 

Tambien:
- [x] Separar escalas de personalidad y cognitivas en dos bloques separados.

**Comment by nik0lai** [comment]
Esta es la lista de escalas y el código diciendo si quedaron en escalas cognitivas o de personalidad. Si no tienen código es porque no van en esos bloques.

scale |   |   |   | per_cog
-- | -- | -- | -- | --
a priori screening belief |   |   |   |  
beck anxiety inventory |   |   |   | per
big five inventory |   |   |   | per
cognitive reflection test 7-items multiple choice |   |   |   | cog
general decision making style |   |   |   | per
abbreviated mathematics anxiety rating scale |   |   |   | cog
multiple stimulus types ambiguity tolerance scale II |   |   |   | per
need for cognition |   |   |   | per
Lipkus numeracy scale |   |   |   | cog
probabilistic reasoning scale |   |   |   | cog
risk avoidance scale |   |   |   | per
risk_propensity_scale |   |   |   | per
severity and emotional reaction |   |   |   | 
sociodemographic scale |   |   |   | soc
subjective numeracy scale |   |   |   | cog
tolerance of ambiguity |   |   |   | per
