### ISSUE TITLE
Pregunta que tanto recomendarías tomar followup

### ISSUE THREAD

**Issue by nik0lai** [gorkang/R_conditions_creation#119]
Tenemos esta pregunta en el followup. Debieramos cambiarla de la misma forma como la cambiamos la del bloque willing to screen:
`How strongly would you recommend her [[NOT]] to take the follow-up test?`
por
`How strongly you think she should [[NOT]] take the follow-up test?`

**Comment by gorkang** [comment]
Buenisimo pillando esto. Si, deberiamos dejar ambas iguales!

**Comment by nik0lai** [comment]
fix.
