### ISSUE TITLE
Nueva version Experimento 1 en Qualtrics

### ISSUE THREAD

**Issue by nik0lai** [gorkang/R_conditions_creation#120]
@gorkang, creo que resolví todas las cosas que estaban decididas. Antes de subir a qualtrics una nueva version (y terminar #112) necesito que resuelvas algunos issues. Estos creo son más críticos que el resto.
#119, #118, #113

**Comment by gorkang** [comment]
Faltarian los siguientes por resolver:

- [ ] #121 
- [ ] #95 
- [ ] #89 
- [ ] #73 
- [ ] #122
- [ ] #123
- [ ] #124
- [ ] #125
