### ISSUE TITLE
Screening question

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#121]
En las preguntas de Screening:

ESTO:
>Of those with a positive test result, how many would you expect to actually have [Down syndrome / breast cancer]?

DEBERIA SER:
>Of those with a positive test result, how many would you expect to actually have [**a fetus with** Down syndrome / breast cancer]?

De lo contrario, parece que preguntamos por el Down de la madre :)

**Comment by nik0lai** [comment]
arreglado!
