### ISSUE TITLE
Shared decision making scale

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#122]
Hay una escala de shared decision making que es muy linda, y bien sencilla de implementar: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5060280/pdf/HEX-8-097.pdf (esto cierra #114).

Abajo dejo una version simplificada de la escala, modificada para incluir la opcion de "numerical information" (se aceptan mejores nombres):

>An ‘invasive medical procedure’ is an intervention that requires that a physician use a device either to inspect an organ visually to look for a medical condition or disease state or to measure the function of an organ or disease state. In addition, there may be a biopsy of a tissue or bodily organ to be sent for pathological analysis to determine whether there is a medical condition or disease state present in the patient. 

>When your physician discusses an invasive medical intervention with you to see if you would want to undertake the intervention, your physician can present you with four types of information:
• Risk information (information about how risky the intervention is to you)
• Benefit information (information about how you would benefit from the intervention)
• Numerical information (information about how common de disease is, accuracy rate and false positives of the test)
• The doctor’s opinion on whether you should undergo the intervention

>Question 1. Which of the above four types of information is most important to you when you are asked to consider undergoing an invasive medical intervention? [present alternatives in RANDOM ORDER]
• Risk information 
• Benefit information 
• Numerical information
• The doctor’s opinion on whether the procedure should be done in your case

>Question 2. When you make decisions in medicine related to invasive medical procedures, who do you prefer to make the decision: [present alternatives in RANDOM ORDER]
• I prefer to make the decision myself
• I prefer to have the doctor make the decision for me
• I prefer to share the decision making with my doctor

**Comment by nik0lai** [comment]
Listo!

**Comment by gorkang** [comment]
Reabro solo para comprobar que la escala tambien aparecera en el book! Si es asi cierralo :)

**Comment by nik0lai** [comment]
Sí está.
