### ISSUE TITLE
Ultimos cambios en fact-box

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#123]
A) Hay un par de numeros visiblemente mal alineados:

1. "Numbers for women aged **20/40** years who did or did not... [primer parrafo arriba]
2. "about **8/55**" [el de harms... deberia bajarse un poquito]  

---

B) Por otro lado, habria que cambiar la frase de harms para que la pregunta se pueda responder:

"How many women experienced false alarms and received additional treatments or had biopsies?" --> "How many women experienced false alarms (**false positive test results**) and received additional treatments or had biopsies?"

**Comment by gorkang** [comment]
Tu ves el 20 asi? 

![screenshot from 2018-11-29 07-00-55](https://user-images.githubusercontent.com/6491790/49214085-9f717880-f3a4-11e8-9e05-41074dea5b88.png)

Si los ves asi, la parte de abajo de los numeros tiene que estar alineada con la parte de abajo de las letras (usar la d de age**d** como referencia). :)

**Comment by nik0lai** [comment]
No, lo veo así (este es el archivo en la carpeta /fbpi/output).
![image](https://user-images.githubusercontent.com/11561730/49220128-98af2980-f3d5-11e8-972d-669e8544eb5f.png)
Este es el link que lleva a la imagen subida a Qualtrics
https://qsharingeu.eu.qualtrics.com/ControlPanel/Graphic.php?IM=IM_6gxo0AnwMN9rSdv

**Comment by nik0lai** [comment]
Quizás si clonas el repositorio de nuevo? La rama master está al día.

**Comment by gorkang** [comment]
Creo que hay alguna variable del compu/paquetes, o lo que sea, pq con una version clonada del repo se sigue viendo rarito.

Cierro el issue dado que en la version de Qualtrics esta OK.
