### ISSUE TITLE
Errores en New Paradigm corregidos - cambiar posicion de frase prevalencia y plot

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#124]
He corregido un par de errores en las imagenes de los New Paradigm, ademas de hacer alguna simplificacion (quitar parrafo inicial por su irrelevancia, etc.)

Dejo aqui los .svg para que los pongas tu en la carpeta y comitees las cosas: [new paradigm.zip](https://github.com/gorkang/R_conditions_creation/files/2617063/new.paradigm.zip) (le ha pasado algo raro a mi carpeta, y me aparece que han cambiado casi todos los archivos, asi q prefiero NO comitear nada).

Como consecuencia, ahora hay dos cosas que quedan fuera de lugar:

- [x] La frase de la prevalencia esta demasiado abajo y se solapa con el texto.
- [x] El plot queda muy abajo

**Comment by nik0lai** [comment]
Arreglado. Ahora la imagen del new paradigm es más corta.

**Comment by gorkang** [comment]
El salto de linea de la frase de la prevalencia se ve mas pequeño que los otros... lo que hace que se vea muy pegado. 

Se que la diferencia es pequeña, pero me resulta muy saliente. Se generoso con ese salto de linea please (mejor que se vea un poco separado que un poco junto). :)

**Comment by nik0lai** [comment]
@gorkang, revísalo ahora y si te parece bien cierra el issue.
