### ISSUE TITLE
Rango de edad en Prenatal Screening - New paradigm

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#125]
Ahora mismo el rango de edad en las graficas (New paradigm) de ambos brochures es 20-60.

En Cancer, esto tiene sentido, pero en prenatal screening no demasiado.

Seria sencillo cambiar el rango de edad solo en prenatal screening, para que solo se vea (20-50)?

**Comment by nik0lai** [comment]
Nada es más sencillo que no hacer nada.
Arreglé los gráficos. Échales una mirada y si te parece bien cierra el issue.

**Comment by gorkang** [comment]
<3
