### ISSUE TITLE
Add Uncertainty Scale

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#128]
We should think about including the uncertainty scale we are preparing with Imke in this experiment.

- It makes sense to include it at the end of the experiment? (maybe using 1 just of the two contexts the participant saw)

The scale should be ready next week. So we can get the first pilot of this without the uncertainty scale, and get in in afterwards... maybe.

**Comment by nik0lai** [comment]
Dónde pongo esto, en el bloque de screening, con las escalas? 
Los items 3, 4 y 5 se duplican (uno por cada condición)?

**Comment by gorkang** [comment]
Mmmm... estoy mirando el protocolo, y creo que tal vez es mejor NO incluir esta escala. Tenemos willing to  screen, que mide una version de esto. Ignorar!
