### ISSUE TITLE
Sensitivity se solapa con el ultimo rango de la respuesta global intuitiva

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#129]
La tasa de aciertos de varias condiciones (~90/95%) esta en el ultimo rango de la respuesta global intuitiva (81-100), igual que el PPV normativo (~83%), lo que hace que contemos como aciertos las respuestas basadas en la tasa de aciertos del test.

Cambiar numeros para que los PPVs normativos altos sean 79-80%.

Una vez se cambien, revisar que quedaron bien todas las condiciones.

**Comment by gorkang** [comment]
**VIGILAR numero de decimales**. Es posible que pasemos de 2% a 1.9%, pero si se esta redondeado, el 1.9 se veria como 2.

**Comment by gorkang** [comment]
He modificado los numeritos para que la respuesta correcta del PPV bajo este en 21% y la del PPV alto en 80%. De este modo, nos aseguramos que caigan en un intervalo distinto a Sensitvities (ahora ~95/98).

De nuevo, no hago commit del numbers_bayes (adjunto aqui), para no cagarla. Espero a que lo comitees tu para reconstruir tpdp.

[numbers_bayes.zip](https://github.com/gorkang/R_conditions_creation/files/2634501/numbers_bayes.zip)

Una vez lo cambies, asigname este issue para que revise de nuevo todos los calculos, pero creo que deberian estar ok.

**Comment by gorkang** [comment]
La unica duda que me queda es que la prevalencia (20 de 2000) y la tasa de aciertos (19 de 20) estan muy cercanos al PPV (21). Esto casi seguro va a hacer que alguna gente diga 19 o 20 por los motivos erroneos y lo demos como acierto. Segun Gig 1995 ~3% de la gente da la prevalencia como respuesta.

REVISAR YO!

**Comment by gorkang** [comment]
Todo es hermoso ahora. 

Con este set de numeros no hay solapamiento con algoritmos comunes ni en +-5% de respuesta correcta, ni en rangos cualitativos de respuesta.

**Podrias meter estos numeros, commitearlos y cerrar el issue?**

[numbers_bayes.zip](https://github.com/gorkang/R_conditions_creation/files/2644931/numbers_bayes.zip)

**Comment by nik0lai** [comment]
listo!
