### ISSUE TITLE
Follow-up english correction

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#130]
Un nativo reviso la escala de razones post Follow-up usada por Imke (que se saco de este expe).

Quedo asi:

Which factors influenced your previous response (How strongly you think she should ${e://Field/should_she_0} take the screening test?).
[0: No influence at all - 100: Completely Influenced ]
    • How informative the [Prenatal screening test/ Mammogram] brochure is
    • How confident you are in the results of the [Prenatal screening test/ Mammogram]
    • The need to confirm the diagnosis
    • The seriousness of [Down syndrome/ Breast cancer] as a medical condition
    • The risk of procedure-related complications in the follow-up test
    • The seriousness of complications in the follow-up test 
    • The possibility of undetected [Down syndrome / Breast cancer] 
    • The possibility of having a procedure-related [miscarriage because of the amniocentesis/ mastectomy because of the Biopsy]
   • Write down the main factor for you:

**Comment by nik0lai** [comment]
@gorkang,
En el primer item se habla de brochure pero no todas las condiciones tienen brochure. Sería como que tan informativa es la información? 

• How informative the [Prenatal screening test/ Mammogram] **brochure** is

**Comment by nik0lai** [comment]
Listo.
