### ISSUE TITLE
Algun DELETE_THIS en los nombres de variables...

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#133]
Me encontre al menos un DELETE_THIS en nombres de variables...

Por ejemplo: "How strongly you think she should [Field-shoShe_fu_01] take the follow-up test?\n0: Not strongly at all - 100: Very strongly - DELETE_THIS"                           fu_Q02_01_1     

No deberia quedar ninguno en la version final, cierto?

**Comment by gorkang** [comment]
Tb hay en muchas (todas?) las "com_...", por ejemplo, 

com_Q01_01_1 -> What percentage of your monthly income would you pay for a test like this? (0-100%) - **delete_this**

**Comment by nik0lai** [comment]
los borraste? en el archivo que se importa a Qualtrics no veo ninguno. Puede ser que el formato de las opciones se haya estropeado y paso al texto de la pregunta.
Voy a marcar este issue para tenerlo en cuenta cuando importe de nuevo el experimento a qualtrics.

**Comment by gorkang** [comment]
Adjunto el archivo de datos. Ahi puedes ver las preguntas en las que aparece:

[Gorka_4_pilot1_16.zip](https://github.com/gorkang/R_conditions_creation/files/2795586/Gorka_4_pilot1_16.zip)

**Comment by nik0lai** [comment]
Los delete_this aparecen porque ese texto esta en todas las escalas que se formatean como sliders. No se ven porque son texto con tamano cero. Al final hice eso porque asi no tenia que borrar el texto manualmente. En el archivo que mandaste la primera fila es el nombre de variable, y la segunda es el texto de la pregunta. Dejo abierto el issue pero no hay nada que arreglar.
