### ISSUE TITLE
Separate sevEmo questions in different sections/blocks

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#135]
Las preguntas de sevEmo ahora mismo se muestran juntas.

Para evitar cambios de escalas de respuesta, etc. propongo separar en varios bloques.

1. **TITULO: Medical screenings and procedures** [Bloque 1]
    1. Trust in medical screenings AND Disconfort medical procedures [sevEmo13 y sevEmo14; random order, pantallas diferentes]
    2. Should preemptive mastectomy AND Should abortion questions [sevEmo06 y sevEmo12; random order, pantallas diferentes, siempre despues de las 2 preguntas anteriores]

2. **TITULO: How the following medical procedures, issues and conditions make you feel?** [Bloque 2, afraid/worried scale]  [lo de abajo se ordena al azar, se muestra en pantallas diferentes]
    1. breastcancer 
    2. downsyndrome 

3. **TITULO: Rate the following medical procedures, issues and conditions** [Bloque 3, severe/serious scale] [lo de abajo se ordena al azar, se muestra en pantallas diferentes]
    1. breastcancer 
    2. downsyndrome 

**DUDA: Deberiamos tener las definiciones de las cuestiones clave sobre las preguntas, en lugar de EN las preguntas?** 

Related to #134

**Comment by nik0lai** [comment]
Estas preguntas estan abiertas aun? Para no hacer cambios y despues tener que revertirlos. Tambien necesito que indiques el numero de los items porque en la seccion 2 y 3 no entiendo bien que items son los que van.
