### ISSUE TITLE
multiple_stim_types_ambiguity_tolerance_scale solo tiene 16 de 22 items?

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#136]
La escala multiple_stim_types_ambiguity_tolerance_scale esta implementada con 16 items, pero en el pdf 
[mclain1993.pdf](https://github.com/gorkang/R_conditions_creation/files/2737911/mclain1993.pdf) la escala aparece con 22... 

Sabes que ha pasado?

**Comment by gorkang** [comment]
Por si acaso, le hice un OCR al documento para extraer todas las preguntas: 
[OCRd text and RESPONSE.zip](https://github.com/gorkang/R_conditions_creation/files/2737950/OCRd.text.and.RESPONSE.zip)

**Comment by nik0lai** [comment]
Items agregados.
