### ISSUE TITLE
Medical condition 1/2

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#137]
Ahora el titulo **Medical condition 1/2** (y 2/2) se presenta en una pantalla diferente a las instructions: 

"Now you will be presented with information about a medical condition and a test to detect it. Please, read it carefully. In the following screens, you will have to answer some questions about this information."

Deberiamos mostrar ambas en la misma pantalla:

---
**Medical condition 1/2**

Now you will be presented with information about a medical condition and a test to detect it. Please, read it carefully. In the following screens, you will have to answer some questions about this information.

---

**Comment by nik0lai** [comment]
listo.
