### ISSUE TITLE
Separar "How strongly you think she should take the follow-up test" de "Which factors..."

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#138]
Ahora mismo la pregunta "How strongly you think she should take the follow-up test" aparece en la misma pantalla que "Which factors influenced your previous response..." (ver abajo).

Se deberian presentar en pantallas separadas.

![screenshot from 2019-01-10 10-53-43](https://user-images.githubusercontent.com/6491790/50972719-1599ec80-14c6-11e9-9970-e60ae33a6677.png)

**Comment by nik0lai** [comment]
Separadas.
