### ISSUE TITLE
Instrucciones de pruebas de dif ind en negrita

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#140]
Las instrucciones de las pruebas de personalidad y cognitivas aparecen arriba de las pruebas, en el mismo tipo de letra que los items. Poner en negrita las instrucciones. Por ejemplo:

---  

**Please rate to what extent you agree or disagree with the following statements.**

An expert who doesn't come up with a definite answer probably doesn't know too much.
...

**Comment by nik0lai** [comment]
Listo.
