### ISSUE TITLE
Include age of women!

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#147]
When we ask a question about "a woman" we always have to include the age of the woman.

For example:

> If  **a woman** receives a positive test result, how likely is that she actually ${e://Field/comp_02_0}? (0-100%)
Should be:

> If  **a [20/40] years old woman** receives a positive test result, how likely is that she actually ${e://Field/comp_02_0}? (0-100%)

---

Another example:

> How many **women** would you expect to have Down syndrome? (0-100%)
Should be:

> How many **[20/40] women** would you expect to have Down syndrome? (0-100%)

But in fact, this last one SHOULD BE:

> What percentage of **[20/40] pregnant women carry fetuses with** Down syndrome? (0-100%)

**Comment by nik0lai** [comment]
Solo me falta esta (no puedo encontrarla)
What percentage of [20/40] pregnant women carry fetuses with Down syndrome? (0-100%)

**Comment by nik0lai** [comment]
Creo que solucione esto ya en #148.
