### ISSUE TITLE
In the Down Syndrome problem, Women should be pregnant women

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#148]
In the DS problems we have things like:

> How many **women** would you expect to have Down syndrome? (0-100%)

But want to say **pregnant women [that carry/carrying] fetuses with Down syndrome**... or similar.

The previous example could be replaced by [see #147]:

> What percentage of **[20/40] pregnant women** carry fetuses with Down syndrome? (0-100%)

---

- [ ] Correct previous case
- [ ] Review to find more instances of this.

**Comment by nik0lai** [comment]
Asi quedo la pregunta:
What percentage of [20/40] years old pregnant women carry fetuses with Down syndrome? (0-100%)
What percentage of [20/40] years old women would you expect to have breast cancer? (0-100%)
