### ISSUE TITLE
Revisar coherencia de SI/NO y pregunta posterior.

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#149]
Dafina completo el experimento e indico que hubo una incoherencia entre su respuesta y la pregunta posterior.

Sus notas no son taaan sencillas de entender, pero... Comenta algo sobre la pregunta siguiente:
> Which factors influenced your previous response (How strongly you think she should take the screening test?). 0: No influence at all - 100: Completely influenced

Y a continuacion indica esto:

> (Programming: My choice did not coincide with the question though. I had chosen that she should not do it, but the question referred to her doing it). Probablemente n Down

Finalmente, hablando del escenario de Breast cancer dice:

> In this scenario the question again did not coincide with my choice.

Podrias revisar donde podria estar el problema?

**Comment by nik0lai** [comment]
La primera pregunta es la pregunta 3 del follow-up. La pregunta cambia dependiendo de lo que se responde en la pregunta 1 de las preguntas willing to screen. Acabo de revisar y no hay problema en relacion a eso. Es decir, si dices que no se deberia el screening entonces aparece un 'NOT' en la pregunta (y no aparece si se escoge que si deberia hacerse el screening). Para agregar el NOT se usa javascript y Embedded data, por lo que es indiferente de si el problema es de cancer o trisomia.

Ahora lo que puede ser, que tambien lo menciono en #157, en la pregunta 3 del folow-up (la que supuestamente no cambia con la respuesta) depende de la pregunta sobre si la mujer deberia hacerse el screening o no (parte de las preguntas willing to screen) y no a la pregunta que viene justo en la pagina anterior sobre si deberia hacerse el followup. Puede ser que la ubicacion de esta pregunta causa confusion porque no refiere a la ultima vez que te pregunta si la mujer deberia tomar el test.

Habria que decidir si la pregunta esta bien ubicada ahi, o si en realidad se deberia preguntar por los factores del follow-up, pero en cualquiera de los dos casos la pregunta se adapta cuando uno dice si o no.
