### ISSUE TITLE
Tolerance to ambiguity: one question wrong and one missing

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#152]
Parece que la pregunta 13 se mezclo con la 14 y salio un hibrido raro. Hay q cambiar la 13 y añadir la 14. En total la escala tiene 16 preguntas:

- Q13: People who insist upon a yes or no decisions are based upon insufficient information -> 
SHOULD BE: **People who insist upon a yes or no answer just don't know how complicated things really are**

- MISSING Q14: Many of our most important decisions are based upon lnsufficient information

**Comment by nik0lai** [comment]
listo.
