### ISSUE TITLE
Shared decision making scale - error and change

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#153]
## Error

Numerical information (information about how common **de** disease is, accuracy rate and false positives of the test) -> 

- [x] SHOULD BE: Numerical information (information about how common **the** disease is, accuracy rate and false positives of the test)

## Change
Dafina comenta:

> Which of the above four types of information is most important to you when you are asked to consider undergoing an invasive medical intervention?
> Great question! But maybe let people order the options in terms of importance rather than choose just one? I was paralyzed not knowing what to choose.

La version original te hace una primera pregunta (When you read the list below, is one of the three types of information listed the ‘most important’ information that you consider when you have to make a decision on whether to accept or refuse an invasive medical intervention?), y si tu respuesta es No, te deja ordenar (lo q le gustaria hacer a Dafina).

Nosotros en el pasado decidimos simplificarlo para evitar meter logica por ahi.  
Lo que podriamos hacer en su lugar es hacer como si hubieran respondido No a la pregunta anterior. En ese caso, se les permite indicar el orden de preferencia. Quedaria asi:

[AHORA TENEMOS] Which of the above four types of information is most important to you when you are asked to consider undergoing an invasive medical intervention?

[AÑADIRIAMOS ESTAS INSTRUCCIONES]
– If all three types are important to you, please write a ‘1’ by each information type.
– If an item of information is not important to you, write a ‘0’.
– If some other combination of information is important to you, please order the information by placing a ‘1’, ‘2’, or ‘3’ on how you rank the information in terms of their importance to you in your decision making:

[RESPUESTAS ACEPTABLES para cada alternativa]: 0, 1, 2, 3

Se entiende?

**Comment by nik0lai** [comment]
Lo que se puede hacer es convertir las alternativas en sliders con valores del 0 al 4 (son cuatro opciones no tres). Ese slider se tiene que agregar manualmente despues de importar todo. Las instrucciones que agregue son estas (agregue el 4 asumiendo que pusiste 3 por error).

– If all four types are important to you, please write a ‘1’ by each information type.
– If an item of information is not important to you, write a ‘0’.
– If some other combination of information is important to you, please order the information by placing a ‘1’, ‘2’, ‘3’, or '4' on how you rank the information in terms of their importance to you in your decision making:

**Comment by gorkang** [comment]
En la escala original son 3 tipos de informacion... parece que nosotros añadimos "Numerical information" como alternativa... y la verdad es que ni lo recordaba :S

Y si se incluyeran cuadros de texto en lugar de sliders? Eso simplificaria la implementacion?

**Comment by nik0lai** [comment]
Habria que agregar la validacion de respuesta para que reciba solo numeros entre el 1 y el 4 luego de subir todo. Es mas sencillo que la opcion del slider. La pregunta quedo asi. (Si te parece cierra el issue). Los cuadros de texto no se veran en el preview del book.

![image](https://user-images.githubusercontent.com/11561730/56097658-b9e16400-5ef7-11e9-9d82-284def2e1159.png)

**Comment by gorkang** [comment]
Me parece genial.

Tienes ya apuntado en el cheklist lo de "agregar la validacion de respuesta para que reciba solo numeros entre el 1 y el 4 luego de subir todo"?

Si si, puedes cerrar el issue.

**Comment by nik0lai** [comment]
Acabo de descubrir que se pueden validar respuestas usando regexs.
Y si, esta en el checklist la validacion de que cada cuadro de texto solo recibe numeros entre 1 y 4
