### ISSUE TITLE
New paradigm and Fact Box changes

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#154]
## New paradigm

- En el eje vertical ahora se indica "Test reliability". CAMBIAR por "Positive result reliability".

## Fact box
- Quitar "about " en harms. Es el unico numero que tiene un about, y lo unico que hace es confundir.

- Quitar info de overdiagnosis de cabecera en negrita:
  + Among all women taking part in screening, some women's healthy fetuses were overdiagnosed with nonexistent trisomies, and went through unnecessary follow-up tests. **-->** Among all women taking part in screening, some women's healthy fetuses **received false positive results**, and went through unnecessary follow-up tests.

  + Among all women taking part in screening, some **were overdiagnosed with non-progressive cancer** and unnecessarily treated. **-->** Among all women taking part in screening, some **received false positive results and went through unnecessary follow-up tests** .

## Both
- Quitar las citas [por ej: "1 Nicolaides..." o "Gotzche & ..."] de New paradigm y Fact box... es ruido nomas...

**Comment by nik0lai** [comment]
listo.
