### ISSUE TITLE
Incluir de nuevo info de screening antes de "Please answer the following questions about the screening test to detect [Down syndrome / Breast cancer] you just saw."

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#155]
Incluir de nuevo info de screening antes de "Please answer the following questions about the screening test to detect [Down syndrome / Breast cancer] you just saw."

De lo contrario es muy dificil contestar a varias de las preguntas.

**Comment by nik0lai** [comment]
Agregue la intro y el item, sin lo de imagina que 2000 mujeres toman el screening...

![image](https://user-images.githubusercontent.com/11561730/54087983-25fd0500-4359-11e9-85b0-26a56d8edb46.png)

Despues de lo de la imagen vendria el texto 'Please answer the following questions about...'. Este cambio ya esta hecho, si te parece bien cierra el issue.

**Comment by gorkang** [comment]
En el bookdown (master o development?) no veo esto. No al menos en el apartado 14.5 Comprehension.

Donde esta?

**Comment by nik0lai** [comment]
No habia pasado las cosas a master y no se habia agregado la intro y el item a bayes summary. Ahora esta en master. Deberias ver algo asi en bayes summary. Si te parece cierras el issue.

![image](https://user-images.githubusercontent.com/11561730/56097991-9cae9480-5efb-11e9-8a1f-1c2bc16aa34e.png)
