### ISSUE TITLE
Cambios esteticos minimos - tamaño de letra, justificado...

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#156]
## Tamaño de letra
Which factors influenced your previous response (How strongly you think she should take the screening test?).
-Which factors influenced your previous response: "How strongly you think she should take the screening test?"[EN LETRA UN POCO MAS PEQUEÑA?].
0: No influence at all - 100: Completely influenced [letra mas pequeña?]

## Texto justificado?
TEXTO DE ESCALAS PUEDE SER JUSTIFICADO?
-An ‘invasive medical procedure’ is an intervention that requires that a physician use a device either to inspect an organ visually to look for a ...

**Comment by nik0lai** [comment]
Deje asi el tamano de la letra 
![image](https://user-images.githubusercontent.com/11561730/54884315-a3ec0080-4e6f-11e9-96b9-c09032a7ec8a.png)
Dime si te parece ese tamano. Voy a agregar la opcion para dejer pequeno el texto de todas las partes donde se indican las anclas de la escala como aqui.

Quedo justificado el texto de la escala.
