### ISSUE TITLE
(How strongly you think she should [take / NOT take] the screening test?).

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#157]
La pregunta "Which factors influenced your previous response (How strongly you think she should take the screening test?" tendria que adaptarse en funcion de si han respondido YES /NO a si deberia hacerse el test o no. 

- "Which factors influenced your previous response (How strongly you think she should **[take / NOT take]** the screening test?)."

**Comment by nik0lai** [comment]
Esa pregunta se adapta segun la pregunta de si la mujer deberia hacerse el screening: will_Q01_0 ('Should she take the screening test?'). Ahora que lo pienso es raro preguntar por las razones para hacerse o no el screening entre las preguntas del follow-up.
Lo otro es que esa pregunta en realidad es sobre los factores que consideraste para decidir si la mujer deberia hacerse el follow-up y no el screening test. Porque ahora mismo se trata del screening, no del follow-up.

**Comment by gorkang** [comment]
CIERTO!

en lugar de screening deberia decir follow-up!

Cambiar: 
Which factors influenced your previous response: “How strongly you think she should [[NOT]] take the screening test?” -->> Which factors influenced your previous response: “How strongly you think she should [[NOT]] take the **follow-up** test?”

**Comment by gorkang** [comment]
He creado un pull request resolviendo esto. Comprobar que esta ok y combinar con master.
