### ISSUE TITLE
Severity emotion scale: REFORMULACION

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#159]
A continuacion incluyo una reformulacion completa de la Severity emotion scale. Con esto cerramos #134 #135 #145 y #146 , e incluimos el feedback de Dafina.

**IMPORTANTE, copiar y pegar las preguntas tal y como estan aqui (ojala revisando, por si hay algun error). CAMBIAN PRACTICAMENTE TODAS, a veces de maneras no facilmente detectables**

Separamos la Severity emotion scale en 3 bloques, cada uno debe empezar con una pantalla con el titulo que se indica:

## [Bloque 1] TITULO: Medical screenings and procedures 
[Cada pregunta en una pantalla diferente; Random order; OLD sevEmo13 y sevEmo14]  

**sevEmo_01**
Please rate your trust in medical screenings:  
> 0:No trust at all - 100: Total trust

**sevEmo_02**
Please rate your experienced discomfort undergoing medical tests or procedures that may be painful or unpleasant (mammograms, drawing blood, etc.):  
> 0:No discomfort at all - 100: Extremely discomfortable

[Cada pregunta en una pantalla diferente; Random order; **Siempre despues de las 2 preguntas anteriores**; OLD sevEmo06 y sevEmo12]

**sevEmo_03**
Imagine a woman you care about that has breast cancer. How strongly you think she should have a preventive mastectomy (complete removal of a breast to reduce her future risk)?  
> 0:Not strongly at all - 100: Very strongly  

**sevEmo_04**
Imagine a woman you care about that is pregnant with a fetus with Down syndrome. How strongly you think she should have an abortion?  
> 0:Not strongly at all - 100: Very strongly

## [Bloque 2] TITULO: How the following medical procedures, issues, and conditions make you feel?
[Cada pregunta en una pantalla diferente; Random order;  **CAMBIAN OPCIONES DE RESPUESTA Y ESCALA**]  

[breastcancer]  
**sevEmo_05**
To what extent would you feel the following if a woman you care about had breast cancer?  
> Not at all 1 2 3 4 5 6 7 Extremely: Assured, Hopeful, Relieved, Anxious, Afraid, Worried

**sevEmo_06**
Imagine a woman you care about found out that she has a high risk of having breast cancer and decided to have a preventive mastectomy.   
To what extent would you feel the following?  
[SMALLER FONT] A **preventive mastectomy** is the complete removal of a breast to reduce the risk of cancer.  
> Not at all 1 2 3 4 5 6 7 Extremely: Assured, Hopeful, Relieved, Anxious, Afraid, Worried

**sevEmo_07**
Imagine a woman you care about had a mastectomy as a result of procedure-related complications during a biopsy. To what extent would you feel the following?  
[SMALLER FONT] A **procedure-related mastectomy** is the removal of a breast because of complications during a medical procedure (for example, a biopsy).   
[SMALLER FONT] A **biopsy** is a diagnostic test to determine whether a breast mass is cancerous. During a biopsy, a thin needle is inserted into the breast to remove tissue samples from the breast mass.  
> Not at all 1 2 3 4 5 6 7 Extremely: Assured, Hopeful, Relieved, Anxious, Afraid, Worried

[downsyndrome]
**sevEmo_08**
To what extent would you feel the following if a woman you care about is pregnant with a fetus with Down syndrome?  
> Not at all 1 2 3 4 5 6 7 Extremely: Assured, Hopeful, Relieved, Anxious, Afraid, Worried

**sevEmo_09**
Imagine a woman you care about found out that she has a high risk of having a child with Down syndrome and decided to have an abortion.  
To what extent would you feel the following?  
> Not at all 1 2 3 4 5 6 7 Extremely: Assured, Hopeful, Relieved, Anxious, Afraid, Worried

**sevEmo_10**
Imagine a woman you care about had a miscarriage as a result of procedure-related complications during an amniocentesis. To what extent would you feel the following?  
[SMALLER FONT] **Amniocentesis** is a diagnostic test to determine whether a child has Down syndrome where a thin needle is inserted into the uterus through the abdomen to get a sample of amniotic fluid.  
> Not at all 1 2 3 4 5 6 7 Extremely: Assured, Hopeful, Relieved, Anxious, Afraid, Worried

## [Bloque 3] TITULO: Rate the following medical procedures, issues and conditions
[Cada pregunta en una pantalla diferente; Random order]

[breastcancer]
**sevEmo_11**
Please rate breast cancer in the following dimensions:   
> 0:Not at all - 100: Most certainly  Severe, Serious, Unpleasant, Horrible

**sevEmo_12**
Please rate voluntary preventive mastectomy in the following dimensions:   
[SMALLER FONT] A **preventive mastectomy** is the complete removal of a breast to reduce the risk of cancer.  
> 0:Not at all - 100: Most certainly  Severe, Serious, Unpleasant, Horrible

**sevEmo_13**
Please rate procedure-related mastectomy (because of complications during a biopsy) in the following dimensions:  
[SMALLER FONT] A **procedure-related mastectom**y is the removal of a breast because of complications during a medical procedure (for example, a biopsy).   
[SMALLER FONT] A **biopsy** is a diagnostic test to determine whether a breast mass is cancerous. During a biopsy, a thin needle is inserted into the breast to remove tissue samples from the breast mass.  
> 0:Not at all - 100: Most certainly  Severe, Serious, Unpleasant, Horrible

[downsyndrome]
**sevEmo_14**
Please rate a pregnancy with a fetus with Down syndrome in the following dimensions:  
> 0:Not at all - 100: Most certainly  Severe, Serious, Unpleasant, Horrible

**sevEmo_15**
Please rate voluntary abortion in the following dimensions:   
> 0:Not at all - 100: Most certainly  Severe, Serious, Unpleasant, Horrible

**sevEmo_16**
Please rate procedure-related miscarriage (because of complications during amniocentesis) in the following dimensions:    
[SMALLER FONT] **Amniocentesis** is a diagnostic test to determine whether a child has Down syndrome where a thin needle is inserted into the uterus through the abdomen to get a sample of amniotic fluid.  
> 0:Not at all - 100: Most certainly  Severe, Serious, Unpleasant, Horrible

**Comment by nik0lai** [comment]
La escala esta implementada (puedes verla en Bayes summary). Un cambio que hice:
- Las etiquetas de los sliders estan ahora al final de las preguntas entre parentesis, porque si se ponen en los sliders no se ubican en los extremos (esto es lo que hemos hechos en otras escalas).

Otro asunto, parece ser que Qualtrics implemento algo que estaba advertido hace timpo. Si randomizas preguntas en un bloque se ignoran los saltos de pagina y los display logic. Antes nada pasaba, hoy subi el bloque a qualtrics randomize las preguntas y efectivamente ignoro los saltos de paginas. Para solucionarlo tendre que poner cada pregunta en un bloque distinto y randomizar los bloques en el survey flow.

**Comment by nik0lai** [comment]
Ahora si quedó lista la escala y las instrucciones para el randomizado en el checklist. En el summary se ve el texto final.
Aqui puedes ver un ejemplo de como se ven los items.
![image](https://user-images.githubusercontent.com/11561730/62236228-f1085200-b3ce-11e9-9017-c9eec9898159.png)
