### ISSUE TITLE
Factors influenced your decision - Willing to screen

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#161]
Seguir estructura similar en screening y en follow-up. Esto significa añadir preguntas **similares** a las de follow-up en screning (willing to screen).

Deberian ir en Willing to screen, justo despues de **will_Q02_0** (y antes de comprehension).

--- 

Which factors influenced your previous response (How strongly you think she should [NOT] take the **screening** test?).
0: No influence at all - 100: Completely influenced

How informative the mammogram/prenatal screening test is

How confident you are in the results of the mammogram/prenatal screening test

*The need to participate in the routine screening*

The seriousness of breast cancer/Down syndrome as a medical condition

*The risk of a false positive result in the screening test*

*The seriousness of a false positive result in the screening test*

The possibility of undetected breast cancer/Down syndrome

*The possibility of receiving additional treatments because of a false positive result in the screening test*

Write down the main factor for you:

**Comment by nik0lai** [comment]
Listo, puedes ver el texto de la nueva pregunta en bayes_summary y en el checklist esta el convertir en slider y agregar la entrada de texto en write down the main factor for you:
