### ISSUE TITLE
Follow-up: How small/big should this risk be... cambiar intervalo en funcion de la respuesta y condicion

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#162]
Para refinar las opciones de respuesta, y evitar que puedan responder cosas absurdas, necesitamos que el **intervalo** cambie en funcion de su respuesta, y de la condicion:

Como recordatorio, les mostramos una de estas preguntas, en funcion de su respuesta previa:  

[IF 1. == "No"] How small this risk should be for you to recommend it (0-100%)
[IF 1. == "Yes"] How big this risk should be for you NOT to recommend it (0-100%)

Deberiamos cambiar el rango del slider, a partir de lo siguiente:  

--- 

[IF 1. == "Yes"] How big this risk should be for you NOT to recommend it (%)
[1%]: 1 - 100%
[10%]: 10 - 100%

---  

[IF 1. == "No"] How small this risk should be for you to recommend it (%)
[1%]: 0 - 1%
[10%]: 0 - 10%

**Comment by nik0lai** [comment]
Ahora hay cuatro preguntas que dependen de la primera respuesta en el bloque follow-up y del riesgo del follow-up. 
Cual seria la escala de cada slider?
1-100:    min 1, max 100, decimals 0 (99 values)
10-100:  min 10, max 100, decimals 0 (90 values)
0-1:         min 0, max 1, decimals 2 (100 values)
0-10:       min 0 max 10, decimals 1 (100 values)

**Comment by gorkang** [comment]
Creo que es mejor mantener el mismo nivel de detalle en terminos del numero de decimales (siempre 1 decimal). 

Dudo que la gente sea capaz de distinguir entre un 0,1% y un 0,15%... y si lo son, mala suerte, perdemos algo de informacion en uno de los casos.

**Comment by nik0lai** [comment]
Pero los slider que van de 1 a 100 y 10 a 100 también tendrían un decimal?
Lo otro es que los sliders quedan con escalas medias raras por el numero de gridlines.
Quedarían así (en este caso los que van los slider 1-100 y 10-100 no tienen decimales, pero lo puedo cambiar).

![image](https://user-images.githubusercontent.com/11561730/62415995-3e84f900-b633-11e9-8535-2cc79e3f5342.png)

![image](https://user-images.githubusercontent.com/11561730/62416002-552b5000-b633-11e9-932c-702ef873cb61.png)

**Comment by gorkang** [comment]
- Ahora estan invertidas las opciones! Deberian ser:

[IF 1. == "Yes"] How big this risk should be for you NOT to recommend it (%)
[1%]: 1 - 100%
[10%]: 10 - 100%

[IF 1. == "No"] How small this risk should be for you to recommend it (%)
[1%]: 0 - 1%
[10%]: 0 - 10%

Entiendes el error? Si dicen que si la recomendarian, tenemos que darle opciones de respuesta grandes.  Si dicen que no la recomendarian, les damos opciones pequeñas.


- Yo le pondria un decimal a todo para evitar diferencias en precision.

- Por lo que veo, la unica escala rara es la del 1 a 100... No se si se pueden fijar los anchors para que sean 1 10, 20... 90, 100?

**Comment by nik0lai** [comment]
Ahh, los display logic están bien, confundí las escalas de los sliders. Así quedaría cada pregunta, tienen el display logic encima así estamos mas seguros que todo está bien. 
Quedaron todos con un decimal, los anchors de la escala se generan automáticamente, así que habría que cambiarlos con JS.

![Screenshot from 2019-08-04 11-00-49](https://user-images.githubusercontent.com/11561730/62421760-29e24880-b6a7-11e9-87c1-a6528dbba66d.png)

![Screenshot from 2019-08-04 11-03-34](https://user-images.githubusercontent.com/11561730/62421778-87769500-b6a7-11e9-818a-0932ff89a8ea.png)
