### ISSUE TITLE
fix export of pictorial items

### ISSUE THREAD

**Issue by nik0lai** [gorkang/R_conditions_creation#165]
mi version de inkscape cambio y ahora los textos que se agregan a las imagenes estan fuera de lugar.

**Comment by gorkang** [comment]
Yo tengo Inkscape 0.92.3 (2405546, 2018-03-11) en Ubuntu 18.04 y todo parece funcionar OK.

Para que no pierdas tiempo con esto, tal vez puedes instalar la version Inkscape 0.92.3 o yo lanzo el script de construccion del book una vez este todo listo.

**Comment by nik0lai** [comment]
Claramente algo estaba haciendo mal porque termine instalando inkscape usando snap. Instalé la versión que tienes y quedó todo bien. Estamos muy cerca!
