### ISSUE TITLE
Changes in Follow up

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#29]
In https://github.com/gorkang/R_conditions_creation/issues/2 you can see the new proposal for the Follow up. We should discuss it and improve it. In any case, we will need some changes in the code.

In the first part of the follow up:
**1. Information from the screening test problem:**
- [prevalence of the disease; depends on the condition they saw]

That information should directly come from:

- [x]  **Textual problems**
- The first sentence of the problem.
   - For Example... for the Chances condition: "Women with breast cancer who participate in a routine mammogram screening have prevalence_01 chances out of prevalence_02 of having a positive result."

- [x] **Pictorial problems**
- In fact-box: die_all_with out of prev_02 women with screening and die_all_without out of prev_02 women without screening die from all types of cancer. 
- In new paradigm: It is estimated that breast cancer is present in prev_01 out of prev_02 women.]
	

**2. Information from Qualtric responses:**
Not sure if there is a way to know in advance which Qualtrics codes will go here (or at least most of the codes...):

- In your response to the previous problem you said that, of those with positive mammograms, [PREVIOUS_RESPONSE - QUALTRICS CODE(?)] actually have breast cancer.

-  5). [IF 1. == "Yes"] How big the follow-up procedure-related risk of complications should be for you NOT to take it [slider 0-100]
   [IF 1. == "No"] How small the follow-up procedure-related risk of complications should be for you to take it [slider 0-100]

**Comment by nik0lai** [comment]
Partial implementation is now in the development branch. Took a wrong approximation to the problem and try to simply combine problem context, follow up risk, and PPV prob. However, the general structure to generate follow-up items to text files is ready. This message is only to inform about the changes made that were merged into the development branch. Next change will be to include prevalences in follow-up items using the first line of textual items. With pictorial items, however, the information will probably come from number_bayes.xls.
