### ISSUE TITLE
Review scales 

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#4]
**Las escalas tienen que servir para hombres y mujeres**

- [ ] Incluir WARNING al empezar experimento sobre preguntas complejas relacionadas con condiciones medicas, abortos,...

* Scales for (Experimento 1/R_conditions_creation_github/DEV/scales/potential_questions.odt):
    + Actitud hacia aborto
    + Actitud hacia trisomia 21
    + Mastectomia
    + Cancer

* A priori screening beliefs:
Experimento 1/R_conditions_creation_github/DEV/scales/A priori screening belief/a priori screening belief.odt
- Can screening be harmful? (HAY UNA PREGUNTA ASI?)

**Comment by gorkang** [comment]
(Petrova, Garcia-retamero, & Pligt, 2016)⁠
1 – not at all,  to 7 – most certainly
Please rate [Breast cancer / Down syndrome / Mastectomy / Abortion] in the following dimensions:
severe
serious
unpleasant
horrible

1 – not at all,  to 7 – most certainly
To what extent you would feel the following if a woman you care about had [Breast cancer / Down syndrome / a Mastectomy / an Abortion]:
afraid
worried
angry
hopeful
calm

1 – not at all,  to 7 – most certainly
To what extent you would recommend a woman you care about with [Breast cancer / Down syndrome] cancer to go through [a Mastectomy / an Abortion].  



**Items measuring a priori screening beliefs (Petrova, Garcia-retamero, & Pligt, 2016)⁠**
    1. Participating in screening always has more advantages than disadvantages. 
    2. Participating in screening cannot hurt anyone.
    3. In my opinion, it is always better to get screened.
    4. If one has the opportunity, one should always participate in screening.
    5. Foregoing screening is irresponsible.
Inluir: Can screening be harmful? (???)

**Comment by nik0lai** [comment]
We have:
> To what extent you would recommend a woman you care about with breast cancer to go through a mastectomy.
> To what extent you would recommend a woman you care about that is pregnant with a child with Down's syndrome to go through an abortion.

Better?
> To what extent you would recommend an abortion to a women you care about that is pregnant with a child with Down's syndrome.
> To what extent you would recommend an abortion to a women you care about that has breast cancer.

**Comment by gorkang** [comment]
Sounds good to me. Let's see what our imaginary native speaker says about it...

**Comment by nik0lai** [comment]
Closed. This is a native speaker problem now.
