### ISSUE TITLE
Fix number sets

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#5]
* Fix number sets
    + PPVs ~.2 & ~.8
    + Numbers should be the "same" in PRabs, FNabs, PF abs??? (this will solve the following point?) 
    + (PROB) The difference between high/low is now only FP
    + OK? - (FREQ) Numbers change but proportions are the same

**Comment by gorkang** [comment]
Encontre algunos problemas graves en los numeros (e.g. probabilidades eran en /1, no /100, y cosas similares. REVISAR!

**Comment by gorkang** [comment]
@nik0lai la columna (all_positive), q se usa solo para PF, cierto?

**Comment by nik0lai** [comment]
@gorkang . Sí, sólo PF los usa.

**Comment by gorkang** [comment]
Reviewed all number sets for all the conditions and diseases. All OK.

![img_20181130_123548](https://user-images.githubusercontent.com/6491790/49298622-ac719300-f49c-11e8-94c7-9c4b33e5fee9.jpg)
