### ISSUE TITLE
Add question about willingness to undergo screening test

### ISSUE THREAD

**Issue by nik0lai** [gorkang/R_conditions_creation#61]
Add a question after PPV probability question about how willing is the person to undergo the screening test.

**Comment by gorkang** [comment]
Primer draft:

> Imagine a woman you care about is offered to participate a in routine mammogram screening to detect breast cancer as the one you saw before.
> 
> Should she take the screening test? [Yes / No]  
> How strongly would you recommend her to take the screening test. [0-100]

**Comment by nik0lai** [comment]
@gorkang. 
According to your version:
```
"Imagine a woman you care about is offered to participate a in routine mammogram screening to detect **breast cancer** as the one you saw before."
"Imagine a woman you care about is offered to participate a in routine test (?) screening to detect **trisomy 21** as the one you saw before."
```
better?
```
"Imagine a woman you care about is offered to participate a in routine screening test to detect **breast cancer** as the one you saw before."
"Imagine a woman you care about is offered to participate a in routine screening test to detect **trisomy 21** as the one you saw before."

```

**Comment by gorkang** [comment]
Creo que la formulacion inicial simplificada, e indicando "prenatal test" me gusta mas:

> "Imagine a [20/40 years old] woman you care about is offered to participate in the routine mammogram screening to detect breast cancer you just saw."
> "Imagine a [20/40 years old] woman you care about is offered to participate in the routine prenatal test screening to detect trisomy 21 you just saw."

**Comment by nik0lai** [comment]
Se te pasó lo que puse en negritas?
"Imagine a [20/40 years old] woman you care about is offered to participate in the routine mammogram screening to detect breast cancer **as the one** you just saw."
"Imagine a [20/40 years old] woman you care about is offered to participate in the routine prenatal test screening to detect trisomy 21 **as the one** you just saw."

**Comment by nik0lai** [comment]
Age added, and item phrasing adapted.
