### ISSUE TITLE
Individual differences and personality scales

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#63]
Definir escalas a utilizar.
- Necesitamos tanto escalas de diff ind como de personalidad.
- Tener en cuenta el tiempo de cada una de ellas.

**Comment by gorkang** [comment]
Ver documento 2017 - Gorka - Fondecyt/Experimentos/Experimento 1/Individual differences/Individual differences.odt

**Comment by nik0lai** [comment]
Scale list:

- [ ] Numeracy (Lipkus) – 10m
- [ ] Subjective numeracy scale (SNS)
- [ ] Big Five Inventory (BFI) 44 items - 5m
- [ ] Inteligencia fluida (Matrices del WAIS-IV) 10-25m
- [ ] Decision making style (GDMS) (Scott & Bruce, 1995)⁠ - 3m
- [ ] Risk Propensity Scale (RPS) (Meertens & Lion, 2008)⁠ - 1m
- [ ] CRT-7 multiple choice (Sirota & Juanchich, 2018)⁠ - 5m - https://osf.io/mzhyc/
- [ ] Probabilistic Reasoning Scale (PRS) - 7m https://onlinelibrary.wiley.com/doi/abs/10.1002/bdm.2011
- [ ] Short Mathematics Anxiety Rating Scale (sMARS) - 25i
- [ ] Beck Anxiety Inventory (BAI) – 21i
- [ ] Need for Cognition (NFC)
- [ ] Risk Avoidance Scale (RAS), one sub-scale of the Personality/Attitude Schedule (Shure & Meeker, 1967)⁠

**Comment by nik0lai** [comment]
Issues to solve: #82, #80, #81, #84.

**Comment by nik0lai** [comment]
see issues: #83 #79

**Comment by gorkang** [comment]
Decidimos no incluir matrices WAIS para poder incluir mas pruebas de personalidad. Tenemos CRT y Numeracy como proxy de habilidades cognitivas. En el Experimento 2 si deberiamos incluir matrices WAIS.
