### ISSUE TITLE
Follow-up question: how small/big to reccomend/not to recommend

### ISSUE THREAD

**Issue by nik0lai** [gorkang/R_conditions_creation#71]
We have:
```
Remember the biopsy has a 1/10% procedure-related risk of complications:
How small this risk should be for you to recommend it (0-100%)?
How big this risk should be for you NOT to recommend it (0-100%)?
```
Better?

```
Remember the biopsy has a 1/10% procedure-related risk of complications:
What should be the risk for you to recommend her to take it (0-100%)?
What should be the risk for you to recommend her NOT to take it (0-100%)?
```

**Comment by gorkang** [comment]
This is in:

- materials/Question/Follow_up/input/questions_raw/followup_question_06.txt
- materials/Question/Follow_up/input/questions_raw/followup_question_07.txt

Now reads:

Remember the follow-up test has a [1/10]% procedure-related risk of complications:
How small should this risk be for you to recommend it? (0-100%)
How big should this risk be for you NOT to recommend it? (0-100%)

Looks good to me as it is. I find the How small/big helps anchor the response in the right direction.
