### ISSUE TITLE
Comprehension scale

### ISSUE THREAD

**Issue by nik0lai** [gorkang/R_conditions_creation#73]
(taken from issue #6) We are using this questions (all sliders).
Check if ok.

- How informative is the screening test?
- How trustworthy is a positive result in a Breast cancer / Trisomy screening?
- How useful is Breast cancer / Trisomy screening?
- How much risk is there in Breast cancer / Trisomy screening?
- How reliable is the test?
- How likely is a correct positive result?
- How likely is a false positive result?
- If a woman receives a positive test result, how probable is that she actually has breast cancer/is pregnant with a fetus with Trisomy 21?

**Comment by gorkang** [comment]
“If a woman receives a positive test result, how probable is that she actually **has is** pregnant with a fetus with Down's syndrome?”

- [ ] Corregir. [has breast cancer / has a fetus with Down's syndrome]??

**Comment by nik0lai** [comment]
Fixed.
we're using: 

> If a woman receives a positive test result, how probable is that she actually [[has breast cancer | is pregnant with a fetus with Down's syndrome]]?

To further edit the placeholder fillers of comprehension questions go to 
_~/R_condition_creation_GITHUB/R_conditions_creation/materials/fillers.csv_

**Comment by gorkang** [comment]
1. Hay una errata en una de las alternativas:

>If a woman receives a positive test result, how likely is that she actually **has** ${e://Field/comp_02_0}? (0-100%)

2. No veo la ultima de las preguntas de comprension (la de la prevalencia!):

>How many women at age **{FIELD AGE}** [are pregnant with a fetus with Down syndrome / have breast cancer] at the time of the screening?
>SI FUERA SENCILLO DE IMPLEMENTAR: [RESPONSE: ____% OR ______ out of  _____ ](PR ABSOLUTE Y RELATIVE EN %).
>SI FUERA COMPLICADO DE IMPLEMENTAR: [RESPONSE: ______ out of  _____ ] (los que han visto %, pondrian x out of 100)...

**Comment by nik0lai** [comment]
Listo.
La última pregunta quedó con __% (si es formato de presentacion en probabilidades) o en __ out of __ (si el formato de presentacion no es probabilidades). En el book después de la pregunta 8 te van a salir tres preguntas en blanco. Estas son las preguntas que luego en qualtrics se formatean en los tipos de pregunta usando un codigo js.
