### ISSUE TITLE
Incluir variables demograficas

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#77]
Al final del experimento, incluir:
- [x] Variables demograficas (Edad, sexo, nivel de estudios, etc.) 

- Experiencia previa con Mamografia, Breast cancer, prenatal screening, Down S (?). (check #89)

**Comment by nik0lai** [comment]
Education levels?
On previous Surveys we have this options:

> Early Childhood Education
> Primary Education
> Lower Secondary Education
> Upper Secondary Education
> Post-Secondary Non-Tertiary Education
> Short-Cycle Tertiary Education
> Bachelor's or Equivalent level
> Master's or Equivalent level
> Doctoral or Equivalent level
> Not elsewhere classified

Qualtrics suggests this:

> Less than high school
> High school graduate
> Some college
> 2 year degree
> 4 year degree
> Professional degree
> Doctorate

**Comment by gorkang** [comment]
**Usemos las nuestras** (On previous Surveys we have this options). Son mas detalladas. Ademas, hemos visto que la educacion es un buen proxy (incluso mejor que numeracy) para algunas cosas:

> Early Childhood Education
> Primary Education
> Lower Secondary Education
> Upper Secondary Education
> Post-Secondary Non-Tertiary Education
> Short-Cycle Tertiary Education
> Bachelor's or Equivalent level
> Master's or Equivalent level
> Doctoral or Equivalent level
> Not elsewhere classified

**Comment by nik0lai** [comment]
Fixed.
To further edits go to:
_~/R_condition_creation_GITHUB/R_conditions_creation/materials/Scales/input/sociodemographic_scale.txt_
