### ISSUE TITLE
check pilot warning text

### ISSUE THREAD

**Issue by nik0lai** [gorkang/R_conditions_creation#87]
> Warning. This is a pilot experiment.
> At the end of the experiment, there will be a comments section.
> Please, indicate there any error you may find regarding the phrasing, wording, or information that will be presented to you.
> Thank you.

**Comment by gorkang** [comment]
Lo cambie en pilot_warning.txt a:

> This is a pilot study. It is likely that you will find some errors or weirdly phrased sentences.
> 
> At the end of the study, you will find a comments section where you can give us feedback on the errors you may find. Please, during the experiment, do copy/paste in a separate text document anything you find odd and let us know in the final comment section.
> 
> We welcome any comment or suggestion to improve our study.
> 
> Thank you!

**Comment by nik0lai** [comment]
changes confirmed.
