### ISSUE TITLE
tolerance to ambiguity scales instructions

### ISSUE THREAD

**Issue by nik0lai** [gorkang/R_conditions_creation#88]
For both tolerance to ambiguity scales (budner, 1962; mclain, 2009), there are no instructions. I'm using this generic instruction:

> Please rate to what extent you agree or disagree with the following statements.

Budner (1962) says (nothing regarding instructions):

> Both in the pretest and in all succeeding administrations of the scale, respondents were allowed to check off one of six response categories for each Item strongly, moderately, or slightly agree, and strongly, moderately, or slightly disagree On positively worded items, strong agreement was scored 7, moderate agreement, 6, slight agreement, 5, slight disagreement, 3, moderate disagreement, 2, and strong disagreement, 1. Scoring of negative Items was in the reverse direction. All omissions were scored 4 both in the pretest and subsequent administrations of the ambiguity scale, the items randomly distributed in an extended opinion inventory comprising the personality and attitude scales described further on.

mclain (1993) says (nothing regarding instructions):

> The MSTAT-I was designed for Likert responses; the seven response anchors ranged from 1, strongly disagree to 7, strongly agree.

**Comment by gorkang** [comment]
OK!
