### ISSUE TITLE
Previous experience questions

### ISSUE THREAD

**Issue by nik0lai** [gorkang/R_conditions_creation#89]
Check if thist questions are ok:

**What is your previous experience with breast cancer?**
I have minimal or no experience with breast cancer
Someone I know has/had breast cancer
Someone very close to me has/had breast cancer
I personally have/had breast cancer

**What is your previous experience with Down's syndrome?**
I have minimal or no experience with Down's syndrome
Someone I know has Down's syndrome
Someone I know has a child Down's syndrome
Someone very close to me has Down's syndrome
Someone very close to me has a child Down's syndrome

**What is your previous experience with mammograms?**
I have minimal or no experience with mammograms
Someone I know has undergone a mammography
Someone very close to me has undergone a mammography
I personally have undergone a mammography

**What is your previous experience with prenatal screenings?**
I have minimal or no experience with prenatal screenings
Someone I know has undergone a prenatal screening
Someone very close to me has undergone a prenatal screening
I personally have undergone a prenatal screening

**Comment by gorkang** [comment]
**What is your previous experience with breast cancer?**
I have minimal or no experience with breast cancer
Someone I know has/had breast cancer
Someone very close to me has/had breast cancer
I personally have/had breast cancer

**What is your previous experience with Down's syndrome?**
I have minimal or no experience with Down's syndrome
Someone I know has/had a child with Down's syndrome
Someone I know has/had a child with Down's syndrome
Someone very close to me has/had a child with Down's syndrome
Someone very close to me has/had a child with Down's syndrome

**What is your previous experience with mammograms?**
I have minimal or no experience with mammograms
Someone I know has undergone a mammography
Someone very close to me has undergone a mammography
I personally have undergone a mammography

**What is your previous experience with prenatal screenings?**
I have minimal or no experience with prenatal screenings
Someone I know has undergone a prenatal screening
Someone very close to me has undergone a prenatal screening
I personally have undergone a prenatal screening

**Comment by gorkang** [comment]
Not 100% sure about the grammar of the "What is your previous experience with Down's syndrome pregnancies?" questions.

**Comment by nik0lai** [comment]
I'm labelling this issue with "keep_in_mind" and keeping it open.

**Comment by gorkang** [comment]
Por lo que veo, la pregunta "What is your previous experience with Down's syndrome pregnancies?" no esta implementada?: R_conditions_creation_github/_book/previous-experience.html

Te parece mejor esta formulacion? Si si, añadir:


**What is your previous experience with pregnancies where the baby has Down's syndrome?**
I have minimal or no experience with pregnancies where the baby has Down's syndrome
Someone I know has/had a pregnancy where the baby has/had Down's syndrome
Someone very close to me has/had a pregnancy where the baby has/had Down's syndrome
I personally have/had a pregnancy where the baby has/had Down's syndrome

**Comment by nik0lai** [comment]
Me parece bien. Cambié la pregunta y arreglé el preview que estaba algo raro.
