### ISSUE TITLE
Instructions between second screening block and scales?

### ISSUE THREAD

**Issue by nik0lai** [gorkang/R_conditions_creation#90]
Now you will have to answer a series of questions about diverse matters.
Try to do your best.

**Comment by nik0lai** [comment]
Now we're using this:

> Now you will answer some scales about the way you think. Please read carefully and try your best to answer each question.

**Comment by gorkang** [comment]
Lo cambie por:

> Our goal is to understand what drives people to make the decisions they make. Now we will present you a few questionnaires about the way you think. Please, read the statements carefully and do your best to answer sincerely, and to the best of your abilities. As you already know, the responses are strictly confidential.

**Comment by nik0lai** [comment]
I'd remove the "Our goal is to understand what drives people to make the decisions they make". I think people will get too self-conscious.

> Now we will present you a few questionnaires about the way you think. Please, read the statements carefully. Do your best to answer sincerely, and to the best of your abilities. As you already know, the responses are strictly confidential.
