### ISSUE TITLE
Add "women" to prevalences

### ISSUE THREAD

**Issue by nik0lai** [gorkang/R_conditions_creation#91]
Prevalences are forwarded to follow-up item directly from PPV screening items. With the context of "2000 woman participated..." the prevalence alone says things like "0.05% have breast cancer at the time of the screening". Not indicating explicitly that is 0.05% woman.
One simple solution is to add "women" to all prevalences. In that case, only prevalences will refer to women, but hit-rate and false positive rate won't.

**Comment by gorkang** [comment]
Why is this a problem? Could you write down exactly what the participants see?

**Comment by nik0lai** [comment]
When prevalence is presented on nfab, prab, and prre presentation formats, there is no reference to "women". for example:

> ca_prab_ppvlow: 0.01% have breast cancer at the time of the screening.
> ca_prre_ppvhigh: 0.02% have breast cancer at the time of the screening.

So, when prevalence is presented in the follow-up question, it is not explicit that it is referring to women. Although it's pretty much inferable.
Follow-up example:

> Remember that:
> 
> 0.01% have breast cancer at the time of the screening.
> 
> In your response to the previous problem, you said that ${e://Field/ppv_response_0} of those with a positive mammogram/test result actually have the medical condition (breast cancer/Down’s syndrome).
> 
>

**Comment by gorkang** [comment]
Creo que no es necesario introducir women. El contexto lo hace bien evidente, y asi nos ahorramos una palabra.
