### ISSUE TITLE
a priori belief screening position in survey flow

### ISSUE THREAD

**Issue by nik0lai** [gorkang/R_conditions_creation#93]
Where to put a priori belief, before screening blocks, or after screening blocks (with other scales)?

**Comment by gorkang** [comment]
Creo que a priori deberia aparecer al principio, para que podamos evaluar sus creencias a priori, sin ser contaminadas por nuestros tests malos o buenos.

**Comment by nik0lai** [comment]
Position changed on the current qualtrics survey flow and on the script to import text to qualtrics.
