### ISSUE TITLE
severity_emotional_reaction - Voluntary abortion?

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#95]
En severity_emotional_reaction.txt:

"To what extent you would feel the following if a woman you care about had an abortion?"

- Como podriamos asegurarnos que se interpreta como un aborto VOLUNTARIO? (sin afectar a las otras condiciones (mastectomy... )).

**Comment by nik0lai** [comment]
habría que consultarlo con un nativo pero me parece que "abortion" implica la decisión de la madre (o de alguien) mientras que "misscarriege" se usa para un aborto espontaneo.

**Comment by gorkang** [comment]
Si, por lo que veo en wikipedia "Abortion is the ending of pregnancy due to removing an embryo or fetus before it can survive outside the uterus. An abortion that occurs spontaneously is also known as a miscarriage. When deliberate steps are taken to end a pregnancy, it is called an induced abortion".

Tal vez se podria añadir una opcion:(?)

"To what extent you would feel the following if a woman you care about had a procedure-related miscarriage following amniocentesis:"

De ese modo podriamos distinguir entre emocion ante aborto provocado por follow up y aborto por screening?

**Comment by gorkang** [comment]
Sumada a la otra alternativa levemente modificada:

"To what extent you would feel the following if a woman you care about decided to have an abortion?"

**Comment by nik0lai** [comment]
Para agregar esta pregunta:

> "To what extent you would feel the following if a woman you care about had a procedure-related miscarriage following amniocentesis:"

Tendría que hacerse con un display logic en qualtrics porque ahora mismo los items de la escala son iguales excepto por algunas partes que se llenan según si es trisomía o cancer de mamas. Como esta pregunta sólo será para trisomía la única forma que se me ocurre es agregarla a la escala y ponerle un display logic para que se muestre si el contexto es trisomía.

**Comment by gorkang** [comment]
Creo que el issue original esta regular. La pareja de preguntas complementarias habla de procedure-related mastectomy following biopsy / procedure-related misscarriage following amniocentesis:

1.a. `"To what extent you would feel the following if a woman you care about had a procedure-related miscarriage following amniocentesis:"`
1.b. `"To what extent you would feel the following if a woman you care about had a procedure-related mastectomy following the biopsy:"`

Por otro lado, creo que es util poner la pregunta sobre aborto voluntario , para lo cual podriamos tener la pareja:
 
2.a. `"To what extent you would feel the following if a woman you care about decided to have an abortion?"`
2.b. `"To what extent you would feel the following if a woman you care about decided to have a preemptive mastectomy?"`

**Comment by nik0lai** [comment]
2.a. "To what extent you would feel the following if a woman you care about decided to have an abortion?"
2.b. "To what extent you would feel the following if a woman you care about decided to have a preemptive mastectomy?"

En este caso no son lo mismo, cierto? En el caso de trisomía o bien abortas porque (crees que) sabes que tu hijo viene con trisomía, o abortar accidentalmente producto de la biopsia. En el caso de cancer de mamas te haces una mastectomia porque sabes que tienes cancer de mama, o bien porque "crees" o presientes, o sabes que eres más suceptible a tenerla? Me parece que es más simple poner la pareja que sólo una, pero no sé si apuntan a lo mismo.

**Comment by nik0lai** [comment]
Me parece que se le baja el perfil a la evidencia de que tu hijo tiene trisomía. Si me dices tiene alto riesgo para mi no significa que tenga trisomía y si bien eso no hace menos válido el aborto (porque creo que el aborto debiera ser libre) ya no lo justifico por la trisomía. Yo dejaría algo así:

2.a. `"To what extent you would feel the following if a woman you care about decided to have an abortion after knowing she is pregnant with a fetus with Down syndrome?"`
2.b. `"To what extent you would feel the following if a woman you care about decided to have a mastectomy after knowing she has breast cancer?"`

Y las otras dos las dejaría así (porque siento que no queda claro que es involuntario ni producto de complicaciones del procedimiento, es decir, accidental):

1.a. `"To what extent you would feel the following if a woman you care about had a miscarriage as a result of procedure-related complications during the amniocentesis?"`
1.b. `"To what extent you would feel the following if a woman you care about had a mastectomy as a result of procedure-related complications during the breast biopsy?"`

**Comment by gorkang** [comment]
El problema de lo que planteas en 2.a/b es que entonces b no es equivalente a a. Si tienes cancer y no te haces una mastectomia estas suicidandote. Eso es peor que tener un hijo down.

Creo que entiendo lo que dices, pero el objetivo que tenemos aqui es evaluar como de malo les parece el aborto (ante la sospecha de trisomia), y como de mala les parece la mastectomia (ante sospecha). Otra manera de verlo... como de malas les parecen aborto/mastectomia de manera preventiva. Eso creo que nos da informacion util de cara a entender pq despues toman la decision que toman. Recuerda que la decision la toman frente a una sospecha, no una certeza.

Si no te parece muy terrible, lo dejamos asi:
```
1.a. "To what extent you would feel the following if a woman you care about had a miscarriage as a result of procedure-related complications during the amniocentesis?"
1.b. "To what extent you would feel the following if a woman you care about had a mastectomy as a result of procedure-related complications during the breast biopsy?"

2.a. "To what extent you would feel the following if a woman you care about decided to have an abortion after knowing she has a higher risk of having a Down syndrome baby?"
2.b. "To what extent you would feel the following if a woman you care about decided to have a preemptive mastectomy after knowing she has a higher risk of having breast cancer?"
```

**Comment by gorkang** [comment]
Revisando los materiales con Imke, nos dio la impresion de que hay algunos terminos tecnicos que habria que explicar.

Esta el la propuesta de ella. Creo que las opciones de amnio y biopsia tal vez no son ideales...

4.1. "To what extent you would feel the following if a woman you care about had a miscarriage as a result of procedure-related complications during amniocentesis (a diagnostic test to determine whether a child has down syndrome)?": 0: Not at all - 100: Most certainly
→ severe, serious, unpleasant, horrible

4.2. "To what extent you would feel the following if a woman you care about had to have a mastectomy (complete removal of the breast) as a result of procedure-related complications during the biopsy (a diagnostic test to examine the breast tissue) ?
→ severe, serious, unpleasant, horrible

4.3. "To what extent you would feel the following if a woman you care about decided to have an abortion after knowing she has a higher risk of having a Down syndrome baby?": 0: Not at all - 100: Most certainly
→ severe, serious, unpleasant, horrible

4.4. "To what extent you would feel the following if a woman you care about decided to have a preemptive mastectomy (complete removal of the breast) after knowing she has a higher risk of having breast cancer?" 0: Not at all - 100: Most certainly
→ severe, serious, unpleasant, horrible

**Comment by nik0lai** [comment]
el "diagnostic to determine whether ..." me parece un poco inútil. Se supone que esta escala la ven justo después del follow-up. O sea que acaban de leer el followup donde que es necesaria una prueba para confirmar el primer resultado positivo y que esa prueba consiste en la amniocentesis y la biopsia de mamas. Haría los siguientes cambios.
Hay que resolver este issue antes de subir las cosas a Qualtrics porque esto va en Embedded data.

4.1. "To what extent you would feel the following if a woman you care about had a miscarriage as a result of procedure-related complications during amniocentesis (**a biopsy necessary to** determine whether a child has down syndrome)?": 0: Not at all - 100: Most certainly
→ severe, serious, unpleasant, horrible

4.2. "To what extent you would feel the following if a woman you care about had to have a mastectomy (complete removal of the breast) as a result of procedure-related complications during the biopsy of the breast (a diagnostic test **necessary to determine whether a woman has breast cancer**)?
→ severe, serious, unpleasant, horrible

4.3. "To what extent you would feel the following if a woman you care about decided to have an abortion after knowing she has a higher risk of having a Down syndrome baby?": 0: Not at all - 100: Most certainly
→ severe, serious, unpleasant, horrible

4.4. "To what extent you would feel the following if a woman you care about decided to have a preemptive mastectomy (complete removal of the breast) after knowing she has a higher risk of having breast cancer?" 0: Not at all - 100: Most certainly
→ severe, serious, unpleasant, horrible

**Comment by gorkang** [comment]
Tal vez la "Emotion-Severity scale" podria ir al principio del experimento, despues de "A priori belief". De ese modo: 1) Recogemos el parecer de los participantes sin sesgarlos con los materiales 2) Se simplifica (algo) el embedded data.

Que te parece esta redaccion? Dado que estaria al principio, he puesto breves definiciones de las cosas. Tambien he añadido un par de questions que estamos pensando incluir en el expe de Imke.


4.1. "To what extent you would feel the following if a woman you care about had a miscarriage as a result of procedure-related complications during amniocentesis (a diagnostic test to determine whether a child has down syndrome where a thin needle inserted into the uterus through the abdomen to get a sample of amniotic fluid)?": 0: Not at all - 100: Most certainly
→ severe, serious, unpleasant, horrible

4.2. "To what extent you would feel the following if a woman you care about had to have a mastectomy (complete removal of a breast) as a result of procedure-related complications during the biopsy (a diagnostic test to determine whether a breast mass is cancerous where a thin needle is inserted into the breast to remove tissue samples from the breast mass) ?
→ severe, serious, unpleasant, horrible

4.3. "To what extent you would feel the following if a woman you care about decided to have an abortion after knowing she has a higher risk of having a Down syndrome baby?": 0: Not at all - 100: Most certainly
→ severe, serious, unpleasant, horrible

4.4. "To what extent you would feel the following if a woman you care about decided to have a preemptive mastectomy (complete removal of a breast) after knowing she has a higher risk of having breast cancer?" 0: Not at all - 100: Most certainly
→ severe, serious, unpleasant, horrible

4.5. Please rate your trust in medical screenings: 0:No trust at all - 100: Total trust

4.6. Please rate your experienced discomfort with medical procedures: 0: No discomfort at all - 100: Extremely discomfortable

**Comment by nik0lai** [comment]
@gorkang, así quedó la escala, se presenta en un solo bloque sin saltos de página después del a priori screening belief. Hay dos preguntas que creo hay que cambiar, está con negritas la correción.

**sevEmo_01**
Please rate breast cancer in the following dimensions:<br>0: Not at all - 100: Most certainly
**sevEmo_02**
Please rate mastectomy (complete removal of a breast) in the following dimensions:<br>0: Not at all - 100: Most certainly
**sevEmo_03**
To what extent would you feel the following if a woman you care about had breast cancer?<br>0: Not at all - 100: Most certainly
**sevEmo_04**
To what extent would you feel the following if a woman you care about decided to have a preemptive mastectomy (complete removal of a breast) after knowing she has a higher risk of having breast cancer?<br>0: Not at all - 100: Most certainly
**sevEmo_05**
To what extent you would feel the following if a woman you care about had a mastectomy (complete removal of a breast) as a result of procedure-related complications during the biopsy (a diagnostic test to determine whether a breast mass is cancerous where a thin needle is inserted into the breast to remove tissue samples from the breast mass)?<br>0: Not at all - 100: Most certainly
**sevEmo_06**
To what extent would you recommend a preemptive mastectomy (complete removal of a breast) to a woman you care about that had breast cancer?<br>0: Not at all - 100: Most certainly
**CAMBIARÍA ESTA POR:
How strongly you think a women you care about that has breast cancer should has a preemptive mastectomy? 0: Not strongly at all - 100: Very strongly**
**sevEmo_07**
Please rate Down syndrome in the following dimensions:<br>0: Not at all - 100: Most certainly
**sevEmo_08**
Please rate abortion in the following dimensions:<br>0: Not at all - 100: Most certainly
**sevEmo_09**
To what extent would you feel the following if a woman you care about had a child with Down syndrome?<br>0: Not at all - 100: Most certainly
**sevEmo_10**
To what extent would you feel the following if a woman you care about decided to have an abortion after knowing she has a higher risk of having a child with Down syndrome?<br>0: Not at all - 100: Most certainly
**sevEmo_11**
To what extent you would feel the following if a woman you care about had a miscarriage as a result of procedure-related complications during the amniocentesis (a diagnostic test to determine whether a child has down syndrome where a thin needle is inserted into the uterus through the abdomen to get a sample of amniotic fluid)?<br>0: Not at all - 100: Most certainly
**sevEmo_12**
To what extent would you recommend an abortion to a woman you care about that is pregnant with a fetus with Down syndrome?<br>0: Not at all - 100: Most certainly
**CAMBIARÍA ESTA POR:
How strongly you think a women you care about that is pregnant with a fetus with Down syndrome should has an abortion? 0: Not strongly at all - 100: Very strongly**
**sevEmo_13**
Please rate your trust in medical screenings:<br>0: No trust at all - 100: Total trust
**sevEmo_14**
Please rate your experienced discomfort with medical procedures:<br>0: No discomfort at all - 100: Extremely discomfortable

**Comment by gorkang** [comment]
En el experimento que estamos preparando con Imke, hemos "mejorado" las emotion-severity scales (ver abajo). En esencia, damos una breve explicacion de los terminos tecnicos. Mi impresion es que asi nos aseguramos que todo el mundo esta respondiendo a lo mismo. Deberiamos integrar estos cambios en el Expe 1.


`1.a. "To what extent you would feel the following if a woman you care about had a miscarriage as a result of procedure-related complications during amniocentesis (a diagnostic test to determine whether a child has down syndrome where a thin needle inserted into the uterus through the abdomen to get a sample of amniotic fluid)?": 0: Not at all - 100: Most certainly
→ severe, serious, unpleasant, horrible`

`1.b. "To what extent you would feel the following if a woman you care about had to have a mastectomy (complete removal of a breast) as a result of procedure-related complications during the biopsy (a diagnostic test to determine whether a breast mass is cancerous where a thin needle is inserted into the breast to remove tissue samples from the breast mass) ?
→ severe, serious, unpleasant, horrible`

`2.a. "To what extent you would feel the following if a woman you care about decided to have an abortion after knowing she has a higher risk of having a Down syndrome baby?": 0: Not at all - 100: Most certainly
→ severe, serious, unpleasant, horrible`

`2.b. "To what extent you would feel the following if a woman you care about decided to have a preemptive mastectomy (complete removal of a breast) after knowing she has a higher risk of having breast cancer?" 0: Not at all - 100: Most certainly
→ severe, serious, unpleasant, horrible`

`3.a. Please rate your trust in medical screenings: 0:No trust at all - 100: Total trust`
`3.b. Please rate your experienced discomfort with medical procedures: 0: No discomfort at all - 100: Extremely discomfortable`

**Comment by nik0lai** [comment]
@gorkang, el último comentario que hiciste ya lo habías hecho dos comentarios atrás (esos cambios ya están implementados. Por fa lee mi último comentario antes de este donde te dejo unas correcciones que haría.

**Comment by gorkang** [comment]
Bufff... claramente no se puede trabajar con fiebre... :(

Me parece bien cambiar esta.

> sevEmo_10
> To what extent would you feel the following if a woman you care about decided to have an abortion after knowing she has a higher risk of having a Down syndrome baby?
> 0: Not at all - 100: Most certainly
> cambiaría "a Down syndrome baby" por "a child with Down syndrome" porque así lo decimos en otra pregunta.

Quedaria:

> sevEmo_10
> To what extent would you feel the following if a woman you care about decided to have an abortion after knowing she has a higher risk of having a child with Down syndrome?
> 0: Not at all - 100: Most certainly


En cuanto a estas dos, me parece enredado el ingles. Que te parece la siguiente formulacion?

> sevEmo_06
> Imagine a woman you care about that has breast cancer. How strongly you think she should have a preemptive mastectomy (complete removal of a breast)? 0: Not strongly at all - 100: Very strongly
> 
> sevEmo_12
> Imagine a woman you care about that is pregnant with a fetus with Down syndrome. How strongly you think she should have an abortion? 0: Not strongly at all - 100: Very strongly
>

**Comment by nik0lai** [comment]
Me parecen bien.
Arreglado.
