### ISSUE TITLE
positive framework test denomination

### ISSUE THREAD

**Issue by nik0lai** [gorkang/R_conditions_creation#96]
En positive framework, tanto en cancer como pregnant usamos “positive test result” en los otros formatos usamos “positive test result” para down y positive mamogram para cancer, lo cambiamos para homogeneizar?

**Comment by gorkang** [comment]
SI! Cambiarlo en PF para que quede como en las otras condiciones. Gracias!

**Comment by nik0lai** [comment]
En la segunda y tercera pieza de información de positive framework el texto es así para cancer y trisomia:

> the test result is correctly/incorrectly positive

mejor?
**trisomía**
> the prenatal test result is correctly/incorrectly positive

**cancer**
> the mamogram result is correctly/incorrectly positive

No se hace mención de esta forma a los test en las otras condiciones.

**Comment by gorkang** [comment]
Por lo que estoy viendo, la incoherencia va mas alla de la condicion PF.

Porfa revisa sistematicamente las condiciones para dejar todas iguales.

**Comment by nik0lai** [comment]
fixed and pushed.
