### ISSUE TITLE
Factbox - Edad deberia cambiar con la condicion

### ISSUE THREAD

**Issue by gorkang** [gorkang/R_conditions_creation#97]
Ahora mismo se muestra siempre 40 años para prenatal y 50 para cancer. La edad deberia cambiar segun la condicion, igual que en new paradigm...

Ej: "Numbers for women aged **40** years or older* who did or did not participate in prenatal screening..."

En la intro a los problemas de screening se indica:

"Suppose the following statistics are known about women at age **20/40** who participate in a routine prenatal screening test to detect Trisomy 21, a blood test that detects the presence of an extra chromosome 21."
- Ahora mismo hay ocasiones en las que la informacion de la intro es incoherente con la del fact-box. Ej. La intro habla de mujer de 20a, pero el fact-box muestra info de 40a.

**Comment by gorkang** [comment]
Ver issue #7. La forma de los fact-box cambiara bastante para que sea mas compatible con el resto.

**Comment by nik0lai** [comment]
fixed and pushed.
